############################
# --- Required options --- #
############################

title: gjanas
author: Grzegorz Janas
language: pl
description: "Grzegorz Janas - entuzjasta technologii, fan Apple, automatyki domowej, druku 3D i hydroponiki. SysAdmin i DevOps."
keywords: "Grzegorz Janas, gjanas, SysAdmin, DevOps, smart home, Home Assistant, hydroponika, druk 3D, Apple"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Resources:
    - Ptaki: "https://gjanas.com/ptaki"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "grzegorz.janas@outlook.com"
  facebook: grzesiek.tzw
  github: gjanas
  twitter: g_janas
  youtube: "@gjanas"
  reddit: gjanas
  linkedin: janasgrzegorz
  steam: gjanas

###########################
# --- General options --- #
###########################

url-pretty: "gjanas.com"
title-on-all-pages: true
post_search: false
edit_page_button: false
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

################
# --- Misc --- #
################

timezone: "Europe/Warsaw"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-sitemap

# Remove Beautiful Jekyll ads
remove-ads: true
